//! Bundled reference corpus (top npm packages, exfil endpoints).
//!
//! V1 ships a static snapshot of ~150 popular npm names hand-curated
//! from public download-stats lists. A production deployment should
//! refresh this list periodically (npm publishes daily download
//! counts via the registry's `/downloads/range/` endpoint). The
//! list lives here rather than in an external file so the binary
//! works offline.

use monomi_core::Corpus;

const TOP_NPM: &[&str] = &[
    // Standard library staples + framework cores
    "react",
    "react-dom",
    "react-native",
    "react-router",
    "react-router-dom",
    "react-redux",
    "react-scripts",
    "react-query",
    "next",
    "vue",
    "svelte",
    "angular",
    "@angular/core",
    "@angular/common",
    // Build tooling
    "webpack",
    "webpack-cli",
    "webpack-dev-server",
    "babel-loader",
    "esbuild",
    "rollup",
    "vite",
    "vitest",
    "parcel",
    "tsc",
    "typescript",
    "ts-node",
    "tsx",
    // Linters / formatters
    "eslint",
    "prettier",
    "eslint-plugin-react",
    "eslint-plugin-import",
    "eslint-plugin-node",
    "eslint-plugin-prettier",
    "stylelint",
    // Test runners
    "jest",
    "mocha",
    "chai",
    "sinon",
    "supertest",
    "cypress",
    "playwright",
    "puppeteer",
    "nyc",
    "ava",
    // Utility libraries
    "lodash",
    "underscore",
    "ramda",
    "moment",
    "dayjs",
    "date-fns",
    "uuid",
    "semver",
    "ajv",
    "joi",
    "zod",
    "yup",
    "validator",
    "qs",
    "yargs",
    "commander",
    "inquirer",
    "chalk",
    "colors",
    "debug",
    "ora",
    "ms",
    "left-pad",
    "tslib",
    "core-js",
    "reflect-metadata",
    "rimraf",
    "shelljs",
    "fs-extra",
    "glob",
    "minimatch",
    "mime",
    "mime-types",
    "tar",
    "tar-fs",
    "tarball",
    "classnames",
    "prop-types",
    "deep-equal",
    "deep-extend",
    "lru-cache",
    "async",
    "immer",
    "rxjs",
    // HTTP
    "axios",
    "node-fetch",
    "request",
    "got",
    "superagent",
    "undici",
    // Server frameworks
    "express",
    "koa",
    "fastify",
    "hapi",
    "body-parser",
    "cors",
    "helmet",
    "compression",
    "cookie",
    "cookie-parser",
    "http-errors",
    "morgan",
    "multer",
    "nodemailer",
    "passport",
    "jsonwebtoken",
    "ws",
    "socket.io",
    "socket.io-client",
    // DB / caches
    "mongodb",
    "mongoose",
    "mysql",
    "mysql2",
    "pg",
    "redis",
    "ioredis",
    "knex",
    "sequelize",
    "typeorm",
    "prisma",
    "sqlite3",
    // Auth / crypto
    "bcrypt",
    "bcryptjs",
    "crypto-js",
    "argon2",
    // Loggers
    "winston",
    "pino",
    "bunyan",
    "loglevel",
    // Build/dev infra
    "dotenv",
    "cross-env",
    "concurrently",
    "nodemon",
    "npm",
    "yarn",
    "pnpm",
    "lerna",
    "nx",
    "turbo",
    "husky",
    "lint-staged",
    "rimraf",
    // CSS / styling
    "tailwindcss",
    "postcss",
    "autoprefixer",
    "sass",
    "less",
    "styled-components",
    "emotion",
    "@emotion/react",
    "@emotion/styled",
    // Misc data / parsing
    "xml2js",
    "fast-xml-parser",
    "csv-parse",
    "papaparse",
    "marked",
    "remark",
    "cheerio",
    "jsdom",
    "sharp",
    "canvas",
    // Common @types
    "@types/node",
    "@types/react",
    "@types/react-dom",
    "@types/jest",
    "@types/express",
    "@types/lodash",
    "@types/mocha",
];

const KNOWN_EXFIL_HOSTS: &[&str] = &[
    "webhook.site",
    "requestbin.com",
    "requestbin.net",
    "pipedream.net",
    "beeceptor.com",
    "hookbin.com",
    "hookb.in",
    "interact.sh",
    "oast.fun",
    "oast.live",
    "oast.me",
    "oast.site",
    "oast.pro",
    "oast.online",
    "burpcollaborator.net",
    "canarytokens.com",
    "transfer.sh",
    "pastebin.com",
    "ix.io",
    "dpaste.com",
    "dpaste.org",
    "termbin.com",
];

/// Build a `Corpus` from the bundled lists.
pub fn default_corpus() -> Corpus {
    Corpus {
        top_packages: TOP_NPM.iter().map(|s| s.to_string()).collect(),
        known_exfil_hosts: KNOWN_EXFIL_HOSTS.iter().map(|s| s.to_string()).collect(),
    }
}
